CREATE TABLE codeInfo (
	id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	code VARCHAR(100) NOT NULL,
	name VARCHAR(100) NOT NULL COMMENT '코드 이름',
	myDepth INTEGER NOT NULL COMMENT '해당 코드의 depth',	
	preDepthCode VARCHAR(100) COMMENT '부모코드',
	sortNum INTEGER NOT NULL COMMENT '정렬값',
	PRIMARY KEY (id)
);